#!/bin/bash
echo "=== Searching for SFML libraries ==="
echo "In /usr/lib:"
ls -la /usr/lib/libsfml* 2>/dev/null || echo "Not found in /usr/lib"
echo ""
echo "In /usr/local/lib:"
ls -la /usr/local/lib/libsfml* 2>/dev/null || echo "Not found in /usr/local/lib"
echo ""
echo "In /usr/lib/x86_64-linux-gnu:"
ls -la /usr/lib/x86_64-linux-gnu/libsfml* 2>/dev/null || echo "Not found in /usr/lib/x86_64-linux-gnu"
echo ""
echo "=== pkg-config info ==="
pkg-config --list-all 2>/dev/null | grep sfml || echo "No SFML packages registered in pkg-config"
echo ""
echo "=== pkg-config paths for SFML ==="
pkg-config --libs sfml-graphics 2>&1 || echo "pkg-config failed for sfml-graphics"
